server:
  port: 8100

spring:
  rabbitmq:
    host: "localhost"
    port: 5672
#    addresses: "amqp://guest:guest@localhost"
#    virtual-host: /production
#    username: guest
#    password: guest

test:
  amqp:
    direct:
      exchange: "direct-orders-exchange"
      queue: "direct-orders-queue"
    topic:
      exchange: "topic-orders-exchange"
      queue: "topic-orders-queue"
    headers:
      exchange: "headers-orders-exchange"
      queue: "headers-orders-queue"
    fanout:
      exchange: "fanout-orders-exchange"
      queue: "fanout-orders-queue"