server:
  port: 8100

spring:
  rabbitmq:
    addresses: "amqp://admin:secret@localhost"
#    host: "localhost"
#    port: 5672

#    virtual-host: /production
#    username: guest
#    password: guest

test:
  amqp:
    queue: test